apiVersion: v1
kind: ServiceAccount
metadata:
  name: swagger-kubernetes
  namespace: mydlqcloud
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: swagger-kubernetes-role
  namespace: mydlqcloud
rules:
  - apiGroups: [""]
    resources: ["services","endpoints"]
    verbs: ["get","list","watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbac-role-binding
  namespace: mydlqcloud
subjects:
  - kind: ServiceAccount
    name: swagger-kubernetes
    namespace: mydlqcloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: swagger-kubernetes-role
